#include "hermv_csr_n_hi_plain.hpp"
#include "hermv_csr_n_hi_trans_plain.hpp"
#include "hermv_csr_u_hi_plain.hpp"
#include "hermv_csr_u_hi_trans_plain.hpp"
#include "hermv_csr_n_lo_plain.hpp"
#include "hermv_csr_n_lo_trans_plain.hpp"
#include "hermv_csr_u_lo_plain.hpp"
#include "hermv_csr_u_lo_trans_plain.hpp"

#include "hermv_coo_n_hi_plain.hpp"
#include "hermv_coo_n_hi_trans_plain.hpp"
#include "hermv_coo_u_hi_plain.hpp"
#include "hermv_coo_u_hi_trans_plain.hpp"
#include "hermv_coo_n_lo_plain.hpp"
#include "hermv_coo_n_lo_trans_plain.hpp"
#include "hermv_coo_u_lo_plain.hpp"
#include "hermv_coo_u_lo_trans_plain.hpp"

#include "hermv_bsr_n_hi_plain.hpp"
#include "hermv_bsr_n_hi_trans_plain.hpp"
#include "hermv_bsr_u_hi_plain.hpp"
#include "hermv_bsr_u_hi_trans_plain.hpp"
#include "hermv_bsr_n_lo_plain.hpp"
#include "hermv_bsr_n_lo_trans_plain.hpp"
#include "hermv_bsr_u_lo_plain.hpp"
#include "hermv_bsr_u_lo_trans_plain.hpp"

#include "hermv_csc_n_hi_plain.hpp"
#include "hermv_csc_n_hi_trans_plain.hpp"
#include "hermv_csc_u_hi_plain.hpp"
#include "hermv_csc_u_hi_trans_plain.hpp"
#include "hermv_csc_n_lo_plain.hpp"
#include "hermv_csc_n_lo_trans_plain.hpp"
#include "hermv_csc_u_lo_plain.hpp"
#include "hermv_csc_u_lo_trans_plain.hpp"

#include "hermv_dia_n_hi_plain.hpp"
#include "hermv_dia_n_hi_trans_plain.hpp"
#include "hermv_dia_u_hi_plain.hpp"
#include "hermv_dia_u_hi_trans_plain.hpp"
#include "hermv_dia_n_lo_plain.hpp"
#include "hermv_dia_n_lo_trans_plain.hpp"
#include "hermv_dia_u_lo_plain.hpp"
#include "hermv_dia_u_lo_trans_plain.hpp"

#include "hermv_sky_n_hi_plain.hpp"
#include "hermv_sky_n_hi_trans_plain.hpp"
#include "hermv_sky_u_hi_plain.hpp"
#include "hermv_sky_u_hi_trans_plain.hpp"
#include "hermv_sky_n_lo_plain.hpp"
#include "hermv_sky_n_lo_trans_plain.hpp"
#include "hermv_sky_u_lo_plain.hpp"
#include "hermv_sky_u_lo_trans_plain.hpp"
