cmake_minimum_required(VERSION 3.23 FATAL_ERROR)
project("AlphaSparse" LANGUAGES CXX C)
set (CMAKE_CXX_STANDARD 17)

# set(BOOST_ROOT /home/guo.chengxin/boost_1_82_0)
# set(Boost_NO_SYSTEM_PATHS ON)

# find_package(Boost COMPONENTS regex system REQUIRED)
# include_directories(${Boost_INCLUDE_DIRS})

# set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_BUILD_TYPE Release)

set(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")

add_compile_options(-march=native -mtune=native)


set(CMAKE_POSITION_INDEPENDENT_CODE ON)

option(ALPHA_BUILD_CUDA "Compile kernels for NVIDIA GPUs" ${ALPHA_HAS_CUDA})
option(ALPHA_BUILD_HIP "Compile kernels for AMD or NVIDIA GPUs" ${ALPHA_HAS_HIP})
option(ALPHA_BUILD_HYGON "Compile kernels for Hygon CPUs" ${ALPHA_HAS_HYGON})
option(ALPHA_BUILD_ARM "Compile kernels for ARM CPUs" ${ALPHA_HAS_ARM})
option(ALPHA_BUILD_REFERENCE "Compile serial kernels for x86 CPUs" ${ALPHA_HAS_REF})


if(ALPHA_BUILD_CUDA)
    # project("AlphaSparse" LANGUAGES CXX CUDA)
    enable_language(CUDA)
    find_package(CUDAToolkit)
    set (CUDA_ARCH 70)
    # add_definitions(-D__CUDA__)
    add_subdirectory(cuda)    
    string(APPEND CMAKE_CUDA_FLAGS " -gencode=arch=compute_70,code=sm_70")
    string(APPEND CMAKE_CUDA_FLAGS "  -Xcompiler -Wall -fPIC -D_FORCE_INLINES --expt-extended-lambda -use_fast_math --expt-relaxed-constexpr")
    string(APPEND CMAKE_CUDA_FLAGS " -I/home/guochengxin/cusplibrary-cuda10")
endif()
if(ALPHA_BUILD_HIP)    
    enable_language(HIP)
    set (HIP_ARCH 70)
	# set(HIP_CLANG_INCLUDE_PATH /opt/dtk/llvm/lib/clang/15.0.0/lib) #change to the path on your system
    set(HIP_CLANG_INCLUDE_PATH /public/software/compiler/dtk/dtk-23.10/llvm/lib/clang/15.0.0/lib)
    # add_definitions(-D__HIP__)
    find_package(hip REQUIRED)
    find_package(hipsparse REQUIRED)
    find_package(rocprim REQUIRED)
    find_package(rccl REQUIRED)
    find_package(rocsparse REQUIRED)
    include_directories(${HIP_INCLUDE_DIRS})
    add_subdirectory(hip)
endif()
if(ALPHA_BUILD_DCU)    
    enable_language(HIP)
    find_package(HIP REQUIRED)
    include_directories(${HIP_INCLUDE_DIRS})
    set (HIP_ARCH 70)
    # set(HIP_CLANG_INCLUDE_PATH /public/software/compiler/dtk/dtk-23.10/llvm/lib/clang/15.0.0/lib)
    set(CMAKE_CXX_COMPILER hipcc)
    # add_definitions(-D__DCU__)
    set(__HIP_PLATFORM_AMD__ 1)      
    find_package(hipsparse REQUIRED)
    find_package(rocprim REQUIRED)
    find_package(rccl REQUIRED)
    find_package(rocsparse REQUIRED)
    add_subdirectory(dcu)
endif()
if(ALPHA_BUILD_HYGON)    
    message("ALPHA_BUILD_MKL_ENABLE : ${ALPHA_BUILD_MKL_ENABLE}")
    if(ALPHA_BUILD_MKL_ENABLE OR ALPHA_BUILD_PLAIN)
        add_definitions(-D__MKL__)  
    endif()
    enable_language(C ASM)
    find_package(OpenMP REQUIRED)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")

    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fopenmp")
    # string(APPEND CMAKE_CXX_FLAGS " -std=c++17 ")   
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx -march=native") 
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")    
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    add_subdirectory(hygon)
endif()
if(ALPHA_BUILD_ARM)    
    # add_definitions(-D__ARM__)    
    enable_language(C ASM)
    find_package(OpenMP REQUIRED)
    # string(APPEND CMAKE_CXX_FLAGS " -std=c++17 ")    
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    add_subdirectory(arm)
endif()
if(ALPHA_BUILD_PLAIN)    
    add_definitions(-D__PLAIN__)    
    add_definitions(-D__MKL__)  
    find_package(OpenMP REQUIRED)
    # string(APPEND CMAKE_CXX_FLAGS " -std=c++17 ")    
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    add_subdirectory(plain)
endif()

set(OBJECT_LIBS "")

if(ALPHA_BUILD_CUDA)
    list(APPEND OBJECT_LIBS $<TARGET_OBJECTS:alphasparse_cuda>)
endif()

if(ALPHA_BUILD_HYGON)
    list(APPEND OBJECT_LIBS $<TARGET_OBJECTS:alphasparse_hygon>)
endif()

if(ALPHA_BUILD_ARM)
    list(APPEND OBJECT_LIBS $<TARGET_OBJECTS:alphasparse_arm>)
endif()

if(ALPHA_BUILD_PLAIN)
    list(APPEND OBJECT_LIBS $<TARGET_OBJECTS:alphasparse_ref>)
endif()

if(ALPHA_BUILD_HIP)
    list(APPEND OBJECT_LIBS $<TARGET_OBJECTS:alphasparse_hip>)
endif()

if(OBJECT_LIBS)
    add_library(alphasparse SHARED ${OBJECT_LIBS})
else()
    message(WARNING "No source directories are selected for building. No library will be created.")
endif()
