#include "gemm_csr_row_plain.hpp"
#include "gemm_csr_col_plain.hpp"
#include "gemm_csr_row_trans_plain.hpp"
#include "gemm_csr_col_trans_plain.hpp"
#include "gemm_csr_row_conj_plain.hpp"
#include "gemm_csr_col_conj_plain.hpp"

#include "gemm_csc_row_plain.hpp"
#include "gemm_csc_col_plain.hpp"
#include "gemm_csc_row_trans_plain.hpp"
#include "gemm_csc_col_trans_plain.hpp"
#include "gemm_csc_row_conj_plain.hpp"
#include "gemm_csc_col_conj_plain.hpp"

#include "gemm_bsr_row_plain.hpp"
#include "gemm_bsr_col_plain.hpp"
#include "gemm_bsr_row_trans_plain.hpp"
#include "gemm_bsr_col_trans_plain.hpp"
#include "gemm_bsr_row_conj_plain.hpp"
#include "gemm_bsr_col_conj_plain.hpp"

#include "gemm_coo_row_plain.hpp"
#include "gemm_coo_col_plain.hpp"
#include "gemm_coo_row_trans_plain.hpp"
#include "gemm_coo_col_trans_plain.hpp"
#include "gemm_coo_row_conj_plain.hpp"
#include "gemm_coo_col_conj_plain.hpp"

#include "gemm_dia_row_plain.hpp"
#include "gemm_dia_col_plain.hpp"
#include "gemm_dia_row_trans_plain.hpp"
#include "gemm_dia_col_trans_plain.hpp"
#include "gemm_dia_row_conj_plain.hpp"
#include "gemm_dia_col_conj_plain.hpp"