#include "spmmd_csr_row_plain.hpp"
#include "spmmd_csr_row_trans_plain.hpp"
#include "spmmd_csr_col_plain.hpp"
#include "spmmd_csr_col_trans_plain.hpp"
#include "spmmd_csr_row_conj_plain.hpp"
#include "spmmd_csr_col_conj_plain.hpp"

#include "spmmd_bsr_row_plain.hpp"
#include "spmmd_bsr_row_trans_plain.hpp"
#include "spmmd_bsr_col_plain.hpp"
#include "spmmd_bsr_col_trans_plain.hpp"
#include "spmmd_bsr_row_conj_plain.hpp"
#include "spmmd_bsr_col_conj_plain.hpp"

#include "spmmd_csc_row_plain.hpp"
#include "spmmd_csc_row_trans_plain.hpp"
#include "spmmd_csc_col_plain.hpp"
#include "spmmd_csc_col_trans_plain.hpp"
#include "spmmd_csc_row_conj_plain.hpp"
#include "spmmd_csc_col_conj_plain.hpp"