#include "csr/trsm_csr_n_hi_col_plain.hpp"
#include "csr/trsm_csr_n_hi_row_plain.hpp"
#include "csr/trsm_csr_n_lo_col_plain.hpp"
#include "csr/trsm_csr_n_lo_row_plain.hpp"
#include "csr/trsm_csr_u_hi_col_plain.hpp"
#include "csr/trsm_csr_u_hi_row_plain.hpp"
#include "csr/trsm_csr_u_lo_col_plain.hpp"
#include "csr/trsm_csr_u_lo_row_plain.hpp"

#include "csr/trsm_csr_n_hi_col_trans_plain.hpp"
#include "csr/trsm_csr_n_hi_row_trans_plain.hpp"
#include "csr/trsm_csr_n_lo_col_trans_plain.hpp"
#include "csr/trsm_csr_n_lo_row_trans_plain.hpp"
#include "csr/trsm_csr_u_hi_col_trans_plain.hpp"
#include "csr/trsm_csr_u_hi_row_trans_plain.hpp"
#include "csr/trsm_csr_u_lo_col_trans_plain.hpp"
#include "csr/trsm_csr_u_lo_row_trans_plain.hpp"

#include "csr/trsm_csr_n_hi_col_conj_plain.hpp"
#include "csr/trsm_csr_n_hi_row_conj_plain.hpp"
#include "csr/trsm_csr_n_lo_col_conj_plain.hpp"
#include "csr/trsm_csr_n_lo_row_conj_plain.hpp"
#include "csr/trsm_csr_u_hi_col_conj_plain.hpp"
#include "csr/trsm_csr_u_hi_row_conj_plain.hpp"
#include "csr/trsm_csr_u_lo_col_conj_plain.hpp"
#include "csr/trsm_csr_u_lo_row_conj_plain.hpp"

#include "csr/diagsm_csr_n_col_plain.hpp"
#include "csr/diagsm_csr_n_row_plain.hpp"
#include "csr/diagsm_csr_u_col_plain.hpp"
#include "csr/diagsm_csr_u_row_plain.hpp"

#include "bsr/trsm_bsr_n_hi_col_plain.hpp"
#include "bsr/trsm_bsr_n_hi_row_plain.hpp"
#include "bsr/trsm_bsr_n_lo_col_plain.hpp"
#include "bsr/trsm_bsr_n_lo_row_plain.hpp"
#include "bsr/trsm_bsr_u_hi_col_plain.hpp"
#include "bsr/trsm_bsr_u_hi_row_plain.hpp"
#include "bsr/trsm_bsr_u_lo_col_plain.hpp"
#include "bsr/trsm_bsr_u_lo_row_plain.hpp"

#include "bsr/trsm_bsr_n_hi_col_trans_plain.hpp"
#include "bsr/trsm_bsr_n_hi_row_trans_plain.hpp"
#include "bsr/trsm_bsr_n_lo_col_trans_plain.hpp"
#include "bsr/trsm_bsr_n_lo_row_trans_plain.hpp"
#include "bsr/trsm_bsr_u_hi_col_trans_plain.hpp"
#include "bsr/trsm_bsr_u_hi_row_trans_plain.hpp"
#include "bsr/trsm_bsr_u_lo_col_trans_plain.hpp"
#include "bsr/trsm_bsr_u_lo_row_trans_plain.hpp"

#include "bsr/trsm_bsr_n_hi_col_conj_plain.hpp"
#include "bsr/trsm_bsr_n_hi_row_conj_plain.hpp"
#include "bsr/trsm_bsr_n_lo_col_conj_plain.hpp"
#include "bsr/trsm_bsr_n_lo_row_conj_plain.hpp"
#include "bsr/trsm_bsr_u_hi_col_conj_plain.hpp"
#include "bsr/trsm_bsr_u_hi_row_conj_plain.hpp"
#include "bsr/trsm_bsr_u_lo_col_conj_plain.hpp"
#include "bsr/trsm_bsr_u_lo_row_conj_plain.hpp"

#include "bsr/diagsm_bsr_n_col_plain.hpp"
#include "bsr/diagsm_bsr_n_row_plain.hpp"
#include "bsr/diagsm_bsr_u_col_plain.hpp"
#include "bsr/diagsm_bsr_u_row_plain.hpp"

#include "csc/trsm_csc_n_hi_col_plain.hpp"
#include "csc/trsm_csc_n_hi_row_plain.hpp"
#include "csc/trsm_csc_n_lo_col_plain.hpp"
#include "csc/trsm_csc_n_lo_row_plain.hpp"
#include "csc/trsm_csc_u_hi_col_plain.hpp"
#include "csc/trsm_csc_u_hi_row_plain.hpp"
#include "csc/trsm_csc_u_lo_col_plain.hpp"
#include "csc/trsm_csc_u_lo_row_plain.hpp"

#include "csc/trsm_csc_n_hi_col_trans_plain.hpp"
#include "csc/trsm_csc_n_hi_row_trans_plain.hpp"
#include "csc/trsm_csc_n_lo_col_trans_plain.hpp"
#include "csc/trsm_csc_n_lo_row_trans_plain.hpp"
#include "csc/trsm_csc_u_hi_col_trans_plain.hpp"
#include "csc/trsm_csc_u_hi_row_trans_plain.hpp"
#include "csc/trsm_csc_u_lo_col_trans_plain.hpp"
#include "csc/trsm_csc_u_lo_row_trans_plain.hpp"

#include "csc/trsm_csc_n_hi_col_conj_plain.hpp"
#include "csc/trsm_csc_n_hi_row_conj_plain.hpp"
#include "csc/trsm_csc_n_lo_col_conj_plain.hpp"
#include "csc/trsm_csc_n_lo_row_conj_plain.hpp"
#include "csc/trsm_csc_u_hi_col_conj_plain.hpp"
#include "csc/trsm_csc_u_hi_row_conj_plain.hpp"
#include "csc/trsm_csc_u_lo_col_conj_plain.hpp"
#include "csc/trsm_csc_u_lo_row_conj_plain.hpp"

#include "csc/diagsm_csc_n_col_plain.hpp"
#include "csc/diagsm_csc_n_row_plain.hpp"
#include "csc/diagsm_csc_u_col_plain.hpp"
#include "csc/diagsm_csc_u_row_plain.hpp"

#include "coo/trsm_coo_n_hi_col_plain.hpp"
#include "coo/trsm_coo_n_hi_row_plain.hpp"
#include "coo/trsm_coo_n_lo_col_plain.hpp"
#include "coo/trsm_coo_n_lo_row_plain.hpp"
#include "coo/trsm_coo_u_hi_col_plain.hpp"
#include "coo/trsm_coo_u_hi_row_plain.hpp"
#include "coo/trsm_coo_u_lo_col_plain.hpp"
#include "coo/trsm_coo_u_lo_row_plain.hpp"

#include "coo/trsm_coo_n_hi_col_trans_plain.hpp"
#include "coo/trsm_coo_n_hi_row_trans_plain.hpp"
#include "coo/trsm_coo_n_lo_col_trans_plain.hpp"
#include "coo/trsm_coo_n_lo_row_trans_plain.hpp"
#include "coo/trsm_coo_u_hi_col_trans_plain.hpp"
#include "coo/trsm_coo_u_hi_row_trans_plain.hpp"
#include "coo/trsm_coo_u_lo_col_trans_plain.hpp"
#include "coo/trsm_coo_u_lo_row_trans_plain.hpp"

#include "coo/trsm_coo_n_hi_col_conj_plain.hpp"
#include "coo/trsm_coo_n_hi_row_conj_plain.hpp"
#include "coo/trsm_coo_n_lo_col_conj_plain.hpp"
#include "coo/trsm_coo_n_lo_row_conj_plain.hpp"
#include "coo/trsm_coo_u_hi_col_conj_plain.hpp"
#include "coo/trsm_coo_u_hi_row_conj_plain.hpp"
#include "coo/trsm_coo_u_lo_col_conj_plain.hpp"
#include "coo/trsm_coo_u_lo_row_conj_plain.hpp"

#include "coo/diagsm_coo_n_col_plain.hpp"
#include "coo/diagsm_coo_n_row_plain.hpp"
#include "coo/diagsm_coo_u_col_plain.hpp"
#include "coo/diagsm_coo_u_row_plain.hpp"

#include "dia/trsm_dia_n_hi_col_plain.hpp"
#include "dia/trsm_dia_n_hi_row_plain.hpp"
#include "dia/trsm_dia_n_lo_col_plain.hpp"
#include "dia/trsm_dia_n_lo_row_plain.hpp"
#include "dia/trsm_dia_u_hi_col_plain.hpp"
#include "dia/trsm_dia_u_hi_row_plain.hpp"
#include "dia/trsm_dia_u_lo_col_plain.hpp"
#include "dia/trsm_dia_u_lo_row_plain.hpp"

#include "dia/trsm_dia_n_hi_col_trans_plain.hpp"
#include "dia/trsm_dia_n_hi_row_trans_plain.hpp"
#include "dia/trsm_dia_n_lo_col_trans_plain.hpp"
#include "dia/trsm_dia_n_lo_row_trans_plain.hpp"
#include "dia/trsm_dia_u_hi_col_trans_plain.hpp"
#include "dia/trsm_dia_u_hi_row_trans_plain.hpp"
#include "dia/trsm_dia_u_lo_col_trans_plain.hpp"
#include "dia/trsm_dia_u_lo_row_trans_plain.hpp"

#include "dia/trsm_dia_n_hi_col_conj_plain.hpp"
#include "dia/trsm_dia_n_hi_row_conj_plain.hpp"
#include "dia/trsm_dia_n_lo_col_conj_plain.hpp"
#include "dia/trsm_dia_n_lo_row_conj_plain.hpp"
#include "dia/trsm_dia_u_hi_col_conj_plain.hpp"
#include "dia/trsm_dia_u_hi_row_conj_plain.hpp"
#include "dia/trsm_dia_u_lo_col_conj_plain.hpp"
#include "dia/trsm_dia_u_lo_row_conj_plain.hpp"

#include "dia/diagsm_dia_n_col_plain.hpp"
#include "dia/diagsm_dia_n_row_plain.hpp"
#include "dia/diagsm_dia_u_col_plain.hpp"
#include "dia/diagsm_dia_u_row_plain.hpp"

#include "sky/trsm_sky_n_hi_col_plain.hpp"
#include "sky/trsm_sky_n_hi_row_plain.hpp"
#include "sky/trsm_sky_n_lo_col_plain.hpp"
#include "sky/trsm_sky_n_lo_row_plain.hpp"
#include "sky/trsm_sky_u_hi_col_plain.hpp"
#include "sky/trsm_sky_u_hi_row_plain.hpp"
#include "sky/trsm_sky_u_lo_col_plain.hpp"
#include "sky/trsm_sky_u_lo_row_plain.hpp"

#include "sky/trsm_sky_n_hi_col_trans_plain.hpp"
#include "sky/trsm_sky_n_hi_row_trans_plain.hpp"
#include "sky/trsm_sky_n_lo_col_trans_plain.hpp"
#include "sky/trsm_sky_n_lo_row_trans_plain.hpp"
#include "sky/trsm_sky_u_hi_col_trans_plain.hpp"
#include "sky/trsm_sky_u_hi_row_trans_plain.hpp"
#include "sky/trsm_sky_u_lo_col_trans_plain.hpp"
#include "sky/trsm_sky_u_lo_row_trans_plain.hpp"

#include "sky/trsm_sky_n_hi_col_conj_plain.hpp"
#include "sky/trsm_sky_n_hi_row_conj_plain.hpp"
#include "sky/trsm_sky_n_lo_col_conj_plain.hpp"
#include "sky/trsm_sky_n_lo_row_conj_plain.hpp"
#include "sky/trsm_sky_u_hi_col_conj_plain.hpp"
#include "sky/trsm_sky_u_hi_row_conj_plain.hpp"
#include "sky/trsm_sky_u_lo_col_conj_plain.hpp"
#include "sky/trsm_sky_u_lo_row_conj_plain.hpp"

#include "sky/diagsm_sky_n_col_plain.hpp"
#include "sky/diagsm_sky_n_row_plain.hpp"
#include "sky/diagsm_sky_u_col_plain.hpp"
#include "sky/diagsm_sky_u_row_plain.hpp"