#include "trmv_csr_n_hi_plain.hpp"
#include "trmv_csr_n_hi_trans_plain.hpp"
#include "trmv_csr_u_hi_plain.hpp"
#include "trmv_csr_u_hi_trans_plain.hpp"
#include "trmv_csr_n_lo_plain.hpp"
#include "trmv_csr_n_lo_trans_plain.hpp"
#include "trmv_csr_u_lo_plain.hpp"
#include "trmv_csr_u_lo_trans_plain.hpp"

#include "trmv_csr_n_hi_conj_plain.hpp"
#include "trmv_csr_u_hi_conj_plain.hpp"
#include "trmv_csr_n_lo_conj_plain.hpp"
#include "trmv_csr_u_lo_conj_plain.hpp"

#include "trmv_csc_n_hi_plain.hpp"
#include "trmv_csc_n_hi_trans_plain.hpp"
#include "trmv_csc_u_hi_plain.hpp"
#include "trmv_csc_u_hi_trans_plain.hpp"
#include "trmv_csc_n_lo_plain.hpp"
#include "trmv_csc_n_lo_trans_plain.hpp"
#include "trmv_csc_u_lo_plain.hpp"
#include "trmv_csc_u_lo_trans_plain.hpp"

#include "trmv_csc_n_hi_conj_plain.hpp"
#include "trmv_csc_u_hi_conj_plain.hpp"
#include "trmv_csc_n_lo_conj_plain.hpp"
#include "trmv_csc_u_lo_conj_plain.hpp"

#include "trmv_coo_n_hi_plain.hpp"
#include "trmv_coo_n_hi_trans_plain.hpp"
#include "trmv_coo_u_hi_plain.hpp"
#include "trmv_coo_u_hi_trans_plain.hpp"
#include "trmv_coo_n_lo_plain.hpp"
#include "trmv_coo_n_lo_trans_plain.hpp"
#include "trmv_coo_u_lo_plain.hpp"
#include "trmv_coo_u_lo_trans_plain.hpp"

#include "trmv_coo_n_hi_conj_plain.hpp"
#include "trmv_coo_u_hi_conj_plain.hpp"
#include "trmv_coo_n_lo_conj_plain.hpp"
#include "trmv_coo_u_lo_conj_plain.hpp"

#include "trmv_bsr_n_hi_plain.hpp"
#include "trmv_bsr_n_hi_trans_plain.hpp"
#include "trmv_bsr_u_hi_plain.hpp"
#include "trmv_bsr_u_hi_trans_plain.hpp"
#include "trmv_bsr_n_lo_plain.hpp"
#include "trmv_bsr_n_lo_trans_plain.hpp"
#include "trmv_bsr_u_lo_plain.hpp"
#include "trmv_bsr_u_lo_trans_plain.hpp"

#include "trmv_bsr_n_hi_conj_plain.hpp"
#include "trmv_bsr_u_hi_conj_plain.hpp"
#include "trmv_bsr_n_lo_conj_plain.hpp"
#include "trmv_bsr_u_lo_conj_plain.hpp"

#include "trmv_dia_n_hi_plain.hpp"
#include "trmv_dia_n_hi_trans_plain.hpp"
#include "trmv_dia_u_hi_plain.hpp"
#include "trmv_dia_u_hi_trans_plain.hpp"
#include "trmv_dia_n_lo_plain.hpp"
#include "trmv_dia_n_lo_trans_plain.hpp"
#include "trmv_dia_u_lo_plain.hpp"
#include "trmv_dia_u_lo_trans_plain.hpp"

#include "trmv_dia_n_hi_conj_plain.hpp"
#include "trmv_dia_u_hi_conj_plain.hpp"
#include "trmv_dia_n_lo_conj_plain.hpp"
#include "trmv_dia_u_lo_conj_plain.hpp"

#include "trmv_sky_n_hi_plain.hpp"
#include "trmv_sky_n_hi_trans_plain.hpp"
#include "trmv_sky_u_hi_plain.hpp"
#include "trmv_sky_u_hi_trans_plain.hpp"
#include "trmv_sky_n_lo_plain.hpp"
#include "trmv_sky_n_lo_trans_plain.hpp"
#include "trmv_sky_u_lo_plain.hpp"
#include "trmv_sky_u_lo_trans_plain.hpp"

#include "trmv_sky_n_hi_conj_plain.hpp"
#include "trmv_sky_u_hi_conj_plain.hpp"
#include "trmv_sky_n_lo_conj_plain.hpp"
#include "trmv_sky_u_lo_conj_plain.hpp"

